### ISSUE TITLE
Hide supporter options on registration page (I think)

### ISSUE THREAD

**Issue by RobRuana** [magfest/magwest#4]
The following resources are missing; but the "Want to kick in extra?" fields should probably be hidden altogether, considering that we're selling t-shirt and supporter Badge Levels.
```
static/icons/iconshirt.png
static/icons/star.png
static/icons/menace.png
static_views/ribbon.html
static_views/tshirt.html
static_views/keepsakebadge.html
static_views/swagbag.html
static_views/morecowbell.html
static_views/secrets.html
```

![screen shot 2017-04-17 at 3 32 49 pm](https://cloud.githubusercontent.com/assets/2592431/25101859/e5e449de-2383-11e7-97a4-c6a4c0474cf5.png)

**Comment by RobRuana** [comment]
Supporter badge levels and "kick in extra" should be mutually exclusive, right?

**Comment by kitsuta** [comment]
Possibly.

The 'badge level' boxes are, by and large, not really about badges. They're a way to promote kick-in levels.

We could show both kick-in levels and the Supporter badge box -- we did this for MAG 2017, iirc -- because Supporter is such a common kick-in level. It's largely up to the team running MAGWest what they want the page to look like. Some options are:

1. Show only badge levels, e.g., Attendee, T-Shirt, Supporter. Good for if there are very few kick-in levels -- saves a lot of space.
2. Show badge levels + the default dropdown box. Good for if there are a LOT of kick-in levels and we want to 'promote' one or two. We've done this for past MAGPrimes.
3. Show the badge levels + the big kick-in list. Takes up a lot of real estate on the page, but good (we think? no actual testing done) for getting people to select kick-ins as long as we don't have too many kick-in levels.
4. Show just the big kick-in list. This doesn't really save a lot of space, unless we also want to hide the 'attendee' badge box (which is theoretically possible).

**Comment by RobRuana** [comment]
Okay, @migetman9 just submitted [#201](https://github.com/magfest/production-config/pull/201) to resolve #7 and he said:

>  I'm alright with using a dropdown instead of these big buttons for the tiers

**Comment by RobRuana** [comment]
Consensus was reached on slack, and we're going to hide the "kick in" options altogether, and use additional "badge levels" for supporter options.
